import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import CaseHeader from '../../components/CaseHeader'
import { OviModel } from '../../components/CasePlaygrounds'

export const metadata = { title: 'OVI — Pau Ramos', description: 'A private AI productivity system.' }

export default function OviPage() {
  return <main className="case-page case-ovi"><CaseHeader chapter="01 / CURRENT SYSTEM" /><section className="ovi-hero"><p className="kicker">PRIVATE CURRENT SYSTEM / PERFORMANZE</p><h1>OVI</h1><p className="ovi-deck">AI-assisted productivity system. Publicly shown at product level, not client implementation.</p><div className="ovi-orbit" aria-label="Conceptual OVI system map"><strong>OVI</strong><span>ORCHESTRATION</span><span>KNOWLEDGE</span><span>CONTEXT</span><span>ARTIFACTS</span><span>PRODUCT UX</span></div></section><section className="case-split"><p className="case-label">MICROSOFT ECOSYSTEM</p><div><h2>Context becomes product work.</h2><p>OVI connects Microsoft Graph surfaces — Outlook, Teams, Calendar, OneDrive and SharePoint — to AI-assisted workflows. This is a conceptual public architecture, not private production topology. No tenant data, credentials or resource identifiers are public.</p></div></section><OviModel /><section className="case-proof"><div><p className="case-label">ORCHESTRATION</p><p>Intent, Microsoft context, retrieval and artifacts are made legible as one product workflow.</p></div><div><p className="case-label">ARTIFACT GENERATION</p><p>Gamma supports presentation-generation integration inside artifact workflows. No private payloads or generated customer material are public.</p></div></section><section className="ovi-principles"><article><span>01</span><h3>CONTEXT</h3><p>Connect communication, calendar and file context to work in progress.</p></article><article><span>02</span><h3>KNOWLEDGE</h3><p>Use retrieval and embeddings where evidence can inform a useful response.</p></article><article><span>03</span><h3>PUBLIC BOUNDARY</h3><p>No tenant data, credentials, private payloads or exact infrastructure shown.</p></article></section><footer className="case-footer"><Link href="/work/duplex">Next: DUPLEX <ArrowUpRight size={18}/></Link><Link href="/">All systems <ArrowUpRight size={18}/></Link></footer></main>
}
